import Image from "next/image";
import Link from "next/link";
import { OpeningShowcase } from "./components/opening-showcase";
import { ProductCard } from "./components/product-card";
import { RevealController } from "./components/reveal-controller";
import { products } from "./data";

export default function Home() {
  return <><OpeningShowcase /><RevealController /><main>
    <section className="flagship"><div className="flagship-rail"><span>V</span><p>A quiet tribute to freedom<br />Pakistan · 14 August</p><b>AZADI · 1947</b></div><div className="flagship-word" aria-label="Veyra"><span>V</span><span>E</span><span>Y</span><span>R</span><span>A</span></div><div className="flagship-copy reveal"><span>THE AZADI EDITION</span><h1>Made for a life<br />lived in<br /><em>freedom.</em></h1><p className="flagship-note">A quiet celebration of freedom, craft and the objects that carry our stories forward.</p><Link className="text-link" href="/shop">Explore the Azadi Edition <span>↗</span></Link></div><div className="flagship-image image-reveal"><Image src="/images/azadi-serein-hobo.png" alt="Woman carrying the Serein oxblood bag after rain" fill priority sizes="(max-width: 800px) 86vw, 42vw" /><div><span>01</span><p>Serein Hobo<br />Oxblood calfskin</p></div></div></section>
    <section className="house-index"><span>VEYRA ATELIER · AZADI EDITION</span><p>The objects that remember us.</p><span>SCROLL / 01—07</span></section>
    <section className="statement reveal"><p>THE HOUSE / 01</p><h2>We do not make<br />things to stay <em>new.</em></h2><div><p>We make them to stay close. To collect the rain, the hurried mornings, the long walks home—and become evidence that a life was lived.</p><Link href="/story" className="text-link">Enter the atelier <span>↗</span></Link></div></section>
    <section className="new-arrivals section-pad"><div className="section-head"><div><span>02</span><p>Azadi Edition<br />Sixteen numbered forms</p></div><h2>Made to enter<br /><em>your rhythm.</em></h2><Link href="/shop" className="text-link">View all pieces <span>↗</span></Link></div><div className="product-grid featured">{products.slice(0, 3).map((product, index) => <ProductCard product={product} index={index} key={product.slug} />)}</div></section>
    <section className="human-campaign"><article className="campaign-copy reveal"><span>03 · A LIFE IN OBJECTS</span><h2>Time does not<br />damage what<br /><em>was made for it.</em></h2><p>A watch fastened before the house wakes. Shoes that know every stair. A wallet holding a note no one else would keep. This is where our objects become yours.</p><Link href="/shop" className="text-link">Find your everyday piece <span>↗</span></Link></article><figure className="campaign-watch image-reveal"><Image src="/images/azadi-meridian-automatic.png" alt="Man fastening a Veyra Meridian watch in morning light" fill sizes="(max-width: 800px) 100vw, 58vw" /><figcaption><span>THE MERIDIAN</span><p>Not to count the hours.<br />To notice them.</p></figcaption></figure><figure className="campaign-step image-reveal"><Image src="/images/azadi-passage-loafer.png" alt="Leather loafers worn on old stone stairs" fill sizes="(max-width: 800px) 88vw, 34vw" /><figcaption><span>THE PASSAGE</span><p>The finest shoes remember<br />your way home.</p></figcaption></figure></section>
    <section className="edition-marquee" aria-hidden="true"><span>MADE WITH FREEDOM · FULL-GRAIN LEATHER · HAND-FINISHED EDGES · LIFETIME CARE · </span><span>MADE WITH FREEDOM · FULL-GRAIN LEATHER · HAND-FINISHED EDGES · LIFETIME CARE · </span></section>
    <section className="craft-split section-pad"><div className="craft-image image-reveal"><Image src="/images/craft.png" alt="Artisan hand-stitching oxblood leather" fill sizes="(max-width: 800px) 100vw, 58vw" /><span>42 hands · 18 considered steps</span></div><div className="craft-copy reveal"><span>04 · THE MAKING</span><h2>Every edge<br />remembers<br /><em>a hand.</em></h2><p>Saddle stitches pulled one by one. Edges painted, dried, then burnished. Our pieces take the time they require—never the time a schedule demands.</p><dl><div><dt>18</dt><dd>steps from material<br />to finished piece</dd></div><div><dt>01</dt><dd>maker responsible<br />from start to finish</dd></div></dl><Link href="/story" className="text-link">How we make <span>↗</span></Link></div></section>
    <section className="heirloom-story"><div className="heirloom-image image-reveal"><Image src="/images/azadi-lune-frame.png" alt="A mother passing a leather purse and wallet to her daughter" fill sizes="(max-width: 800px) 100vw, 55vw" /></div><div className="heirloom-copy reveal"><span>05 · WHAT WE PASS ON</span><blockquote>“She gave me the purse.<br />The stories were already inside.”</blockquote><p>Good objects outlive the moment they were bought. They return as a familiar weight in another hand.</p><Link href="/shop" className="button dark">Discover small forms</Link></div></section>
    <section className="quote reveal"><span>VEYRA NOTE Nº 07</span><blockquote>“Luxury is not excess.<br />It is the absence of compromise.”</blockquote><p>— The atelier journal</p></section>
    <section className="category-banner"><Image src="/images/azadi-pli-mini.png" alt="Woman wearing the chalk Pli purse by a bookshop" fill sizes="100vw" /><div><span>06 · SMALL FORMS</span><h2>Considered<br /><em>in every fold.</em></h2><Link href="/shop" className="button pale">Explore the collection <span>↗</span></Link></div><aside><b>THE PLI MINI</b><span>Chalk calfskin / $720</span></aside></section>
    <section className="service-strip"><div><span>01</span><p>Complimentary delivery</p><small>Worldwide, always.</small></div><div><span>02</span><p>Lifetime atelier care</p><small>Repair before replacement.</small></div><div><span>03</span><p>Private concierge</p><small>A human answer, within one day.</small></div></section>
  </main></>;
}
