import Image from "next/image"; import Link from "next/link"; import { notFound } from "next/navigation";
import { money, products } from "../../data"; import { ProductCard } from "../../components/product-card"; import { ProductActions } from "./product-actions";
export function generateStaticParams(){return products.map(({slug})=>({slug}));}
const detailFor=(category:string)=>category==="Watches"?"/images/detail-watch.png":category==="Footwear"?"/images/detail-footwear.png":"/images/detail-leather.png";
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params, product=products.find((p)=>p.slug===slug);if(!product)notFound();const related=products.filter((p)=>p.category===product.category&&p.slug!==slug).slice(0,3);return <main className="product-page">
<div className="breadcrumbs"><Link href="/shop">Collection</Link><span>/</span><span>{product.category}</span><span>/</span><span>{product.name}</span></div>
<section className="pdp"><div className="pdp-gallery"><figure className={`pdp-image product-image-${product.slug}`}><Image src={product.image} alt={`${product.name} in ${product.tone}, worn in daily life`} fill priority sizes="(max-width: 900px) 100vw, 62vw"/><figcaption>Edition 02 / Made in 64 pieces</figcaption></figure><figure className="pdp-detail-image image-reveal"><Image src={detailFor(product.category)} alt={`The hand-finished materials and craft behind ${product.name}`} fill sizes="(max-width: 900px) 100vw, 31vw"/><figcaption>Made slowly / Finished by hand</figcaption></figure><div className="pdp-object-note"><span>OBJECT {String(products.indexOf(product)+1).padStart(2,"0")} / 16</span><blockquote>“{product.note}”</blockquote><p>Designed to become less perfect,<br/>and more yours.</p></div></div>
<div className="pdp-info"><p>{product.category} · {product.tone}</p><h1>{product.name}</h1><strong>{money(product.price)}</strong><blockquote>{product.note}</blockquote><div className="pdp-description"><p>{product.description}</p><span>Hand-finished in small runs and made to develop a personal patina.</span></div><ProductActions product={product}/><div className="accordions"><details open><summary>Materials <span>+</span></summary><p>{product.material}</p></details><details><summary>Dimensions & fit <span>+</span></summary><p>{product.dimensions}</p></details><details><summary>Delivery & returns <span>+</span></summary><p>Complimentary atelier delivery and returns within 30 days. Every order is wrapped by hand in 1–2 working days.</p></details><details><summary>Lifetime care <span>+</span></summary><p>Repairs, conditioning and hardware care remain available for the life of every numbered piece.</p></details></div></div></section>
<section className="pdp-note"><span>THE MATERIAL</span><h2>Chosen for how<br/>it will <em>live.</em></h2><p>Not coated into perfection. Made to soften, darken, crease and record the years.</p></section>
{!!related.length&&<section className="related-products section-pad"><div className="section-head"><div><span>YOU MAY ALSO KEEP</span><p>From the same family</p></div><h2>Objects that speak<br/><em>the same language.</em></h2></div><div className="product-grid">{related.map((p,i)=><ProductCard product={p} index={i} key={p.slug}/>)}</div></section>}</main>}
