import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { RevealController } from "../components/reveal-controller";

export const metadata: Metadata = { title: "The House" };

export default function StoryPage() {
  return <main className="story-page"><RevealController /><section className="story-hero"><Image src="/images/campaign-heirloom.png" alt="Two generations sharing a Veyra purse" fill priority sizes="100vw" /><div /><span>THE HOUSE · EST. 2024</span><h1>A quiet argument<br /><em>for keeping things.</em></h1></section><section className="story-intro reveal"><span>01 · WHY VEYRA</span><h2>We make fewer things,<br />and ask more of them.</h2><div><p>VEYRA began with a purse our founder’s mother kept for thirty-two years. Its clasp had softened, one corner carried a faint rain mark, and inside was a folded train ticket no one could bring themselves to throw away.</p><p>That object was not pristine. It was precious because it remembered. We built an atelier around making more things worthy of that kind of life.</p></div></section><section className="story-grid section-pad"><div className="story-photo image-reveal"><Image src="/images/campaign-serein.png" alt="Serein bag worn on a rainy morning" fill sizes="(max-width: 800px) 100vw, 48vw" /></div><div className="story-values reveal"><span>02 · OUR PROMISES</span>{[["01","Material before mood"],["02","Hands before volume"],["03","Repair before replace"],["04","Patina before perfection"]].map(([number,title]) => <div key={number}><i>{number}</i><h3>{title}</h3></div>)}</div></section><section className="story-memory"><Image src="/images/campaign-watch.png" alt="Morning ritual with the Meridian watch" fill sizes="100vw" /><div><span>03 · THE EVERYDAY</span><blockquote>We believe ordinary days<br />deserve extraordinary care.</blockquote><p>The morning clasp. The walk to work. The card handed across a cafe table. Design matters most in the moments no one photographs.</p></div></section><section className="story-closing"><p>AN INVITATION</p><h2>Choose slowly.<br /><em>Keep it close.</em></h2><Link href="/shop" className="button pale">Discover Edition 02</Link></section></main>;
}
